### ISSUE TITLE
[Bug] - 'Love' relationship not shown in second contact's 'Family summary' section

### ISSUE THREAD

**Issue by KierenConnell** [monicahq/chandler#263]
Loving the new Monica so far!
I'm building a test vault with the goal of contributing to the documentation.
If this is already known or not required, please discard.

Using the latest docker image, tagged as revision `99eac7722038a845234e7f933fc6f3078020801b`
When adding relationships to contacts, if you define a 'love' relationship with another contact, the second contact does not inherit the same relationship link in the 'Family summary' area.
![image](https://user-images.githubusercontent.com/46445781/198856859-d7e1e94d-f3ed-4b40-8044-e6f690cc0b05.png)
![image](https://user-images.githubusercontent.com/46445781/198856875-f711b092-2605-404c-84d5-ac755c31f917.png)

**Comment by djaiss** [comment]
Thanks so much for this @KierenConnell 

I just saw that you started to fix the documentation which is insane and great.
However, and this is my bad really, I've moved the documentation to gitbook and therefore the new doc repo is https://github.com/monicahq/docs-gitbook and accessible from https://regis-freyd.gitbook.io/docs/ at the moment (we'll take a custom domain later on).
Why? Because I'm sick of having to maintain documentation portals! Gitbook does it way better.
So, I'll try to incorporate all your changes in the new documentation.

**Comment by djaiss** [comment]
That being said, I'll fix this bug.

**Comment by KierenConnell** [comment]
> Thanks so much for this @KierenConnell 
> 
> I just saw that you started to fix the documentation which is insane and great.
> However, and this is my bad really, I've moved the documentation to gitbook and therefore the new doc repo is https://github.com/monicahq/docs-gitbook and accessible from https://regis-freyd.gitbook.io/docs/ at the moment (we'll take a custom domain later on).
> Why? Because I'm sick of having to maintain documentation portals! Gitbook does it way better.
> So, I'll try to incorporate all your changes in the new documentation.

No worries! Monica has been remarkably useful for me personally, so happy to contribute.
If the team is okay with it, I'll definitely do more on the doco front.

**Comment by djaiss** [comment]
> If the team is okay with it, I'll definitely do more on the doco front.

We are! Documentation takes a lot of time to write, and as you've seen, we do a lot of spelling mistakes and grammatical errors, so for sure, we'd love any help we can get :-)
