### ISSUE TITLE
Contacts are not in alphabetical order

### ISSUE THREAD

**Issue by b3nd1k** [monicahq/chandler#477]
If you go to the "Contacts" page. They are not in alphabetical order.

**Comment by djaiss** [comment]
They are indeed listed by the creation date. Is that an issue?

**Comment by b3nd1k** [comment]
If you have a lot of contacts, it would be a lot more organized to have them in alphabetical order. The way I see the contact tabs is similar to how I view contacts on my phone.

**Comment by Martijn-Bos** [comment]
I would argue that ordering on 'last_updated_at' would make sense. Contact they interact most with will be on top.

It might be beneficial to make an order dropdown with for example the following options:
'Last updated'
'A-Z'
'Z-A'


Ideally it remembers last input of user so that contact sorting stays consistent.

**Comment by djaiss** [comment]
> I would argue that ordering on 'last_updated_at' would make sense. Contact they interact most with will be on top.
> 
> It might be beneficial to make an order dropdown with for example the following options: 'Last updated' 'A-Z' 'Z-A'
> 
> Ideally it remembers last input of user so that contact sorting stays consistent.

This is what I'll do then.

**Comment by djaiss** [comment]
#481 will achieve this.

**Comment by djaiss** [comment]
Done.

The store setting is stored at the user level.

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/61099/236462933-27af41a0-ed67-4d17-bbae-036acf19c3a6.png">
